pipeline {  
  agent any 
  tools {
    maven 'maven_3'
  }

  stages{
          stage(' Building Maven  project ' ){
            steps {
                //checkout scmGit(branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/YahyaLafdi/summer-interns/']])
              sh 'cd KitCoop'
               ////test //sh ' mvn clean install '
            }
          }


    
  }

  
}
