pipline {  
  agent any
  tools {
    maven 'maven_3'
  }

  stages{
          stage(' Building Maven  project ' ){
            steps {
                checkout scmGit(branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/YahyaLafdi/summer-interns/']])
                sh ' mvn clean install '
            }
          }


    
  }

  
}
